### ISSUE TITLE
[EPIC] Navigation

### ISSUE THREAD

**Issue by JohnnySonTrinh** [JohnnySonTrinh/coach-api#1]
- [x] As a user, I can view a navbar from every page so that I can navigate easily between pages.
- [x] As a user, I can navigate Through pages quickly so that I can view content seamlessly without page refresh
- [x] As a logged out user, I can see sign in and sign up options so that I can sign in/up
- [x] As a user, I can view user's avatars so that I can easily identify users of the application
