### ISSUE TITLE
[EPIC] Authentication

### ISSUE THREAD

**Issue by JohnnySonTrinh** [JohnnySonTrinh/coach-api#2]
- [ ] As a user, I can create a new account so that i can access functionality for logged in users. (Sign-up)
- [ ] As a user, I can sign in to the app so that I can access functionality for logged in users. (Sign-in)
- [ ] As a user, I can tell if I'm logged in or not so that I can log in if I need.
- [ ] As a user i can maintain my logged-in status until I choose to log out so that my user experience is not compromised.
