### ISSUE TITLE
[EPIC] Profile

### ISSUE THREAD

**Issue by JohnnySonTrinh** [JohnnySonTrinh/coach-api#8]
- [x] As a user, I can view other users profiles so that I can see their reviews and learn more about them.
- [x] As a user, I cam see a list of the most followed profiles so that I see which profiles are popular.
- [x] As a user, I can view statistics about a specific user: bio number of reviews, follows and users followed so that I can learn more about them.
- [x] As a logged in user, I can follow and unfollow other users so that I can see and remove posts by specific users in my reviews feed.
- [x] As a user, I can view all the reviews by a specific user so that I can catch up on their latest reviews, or decide I want to follow them.
- [x] As a logged in user, I can edit my profile so that I can change my profile picture and bio.
- [x] As a logged in user, I can update my username and password so that I can change my display name and keep my profile secure.
